{% set name = "kneed" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40af95e58bbca3f7897c1a121e5442629e848af23e57cd922ae8a1681d7f9821

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
test:
  imports:
    - kneed
about:
  home: http://github.com/arvkevi/kneed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Knee point detection using Python'

extra:
  recipe-maintainers:
    - arvkevi 
