{% set name = "kneed" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4847ac4f1d04852fea278d5de7aa8bfdc3beb7fbca4a182fec0f0efee43f4b1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.14.2
    - scipy >=1.0.0
test:
  requires:
    - python {{ python_min }}
  imports:
    - kneed
about:
  home: http://github.com/arvkevi/kneed
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Knee point detection using Python

extra:
  recipe-maintainers:
    - arvkevi
